units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 2
  py: ky + 2
  # Double Padding Variables
  dpx: kx + 8
  dpy: ky + 8
  # M2 Screw Inserts
  screwRadius: 1.5
  standoffThickness: 3
  standoffDepth: 3
  # Case
  pcbThickness: 1.6
  baseThickness: 3
  wallThickness: 3
  # Footprints
  rp2040zero_x: 18
  rp2040zero_y: 23.5
  trrs_x: 12
  trrs_y: 6
  boardPadding: 8
points:
  zones:
    matrix:
      anchor:
        shift: [35, -80]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky:
          key:
            splay: 5
        ring:
          key:
            stagger: 0.33ky
            splay: -5
            spread: 1kx + 2
        middle:
          key:
            stagger: 0.33ky
        index:
          key:
            stagger: -0.33ky
            splay: -5
            spread: 1kx + 1
        outer:
          key:
            stagger: -0.2ky
            spread: 1kx + 1
      rows:
        bottom:
        middle:
        top:
    thumbs:
      key:
        padding: 1kx
        spread: 1ky
      anchor:
        ref: matrix_index_bottom
        shift: [0.498kx, -1.68ky]
      columns:
        inner:
          key:
            width: 1.5kx
            splay: -12
            rotate: 90
        outer:
          key:
            width: 1.5kx
            splay: 0
            rotate: 90
      rows:
        cluster:
    mcu:
      anchor:
        ref: matrix_outer_top
        shift: [1.317kx, -0.5ky]
      key:
        width: rp2040zero_x
        height: rp2040zero_y
    trrs:
      anchor:
        ref: mcu
        shift: [7, -rp2040zero_x-2]
      key:
        width: trrs_x
        height: trrs_y
    holePinkyTop:
      anchor:
        ref: [matrix_pinky_top]
        shift: [0.5px + 2,0.5py + 1]
    holeMiddleBottom:
      anchor:
        ref: [matrix_middle_bottom]
        shift: [0,-0.5py - 3]
    holeIndexTop:
      anchor:
        ref: [matrix_index_top]
        shift: [-0.2px, 12]
    holeThumbs:
      anchor:
        ref: [thumbs_outer_cluster]
        shift: [-0.5kx - 3, 0.5kx]
  mirror: &mirror
    ref: matrix_index_top
    distance: 130
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: /matrix/
      size: [kx-0.5,ky-0.5]
    - what: rectangle
      where: /thumb/
      size: [1.5kx,ky-0.5]
  boardLeft:
    - what: polygon
      operation: stack
      fillet: 1
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: matrix_outer_top
          shift: [0.5px,0.5py]
        - ref: mcu
          shift: [-rp2040zero_x/2,rp2040zero_y/2+2]
        - ref: mcu
          shift: [rp2040zero_x/2+4,rp2040zero_y/2+2]
        - ref: trrs
          shift: [trrs_x/2,-trrs_y/2]
        - ref: thumbs_outer_cluster
          shift: [0.75px,-0.5py]
        - ref: thumbs_outer_cluster
          shift: [-0.75px,-0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.75px,0.5py]
        - ref: thumbs_inner_cluster
          shift: [0.9px,0.5py]
        - ref: matrix_ring_bottom
          shift: [-0.45px,-0.5py]
        - ref: matrix_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
  boardRight:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_outer_top
          shift: [0.5px,0.5py]
        - ref: mirror_mcu
          shift: [-rp2040zero_x/2,rp2040zero_y/2+2]
        - ref: mirror_mcu
          shift: [rp2040zero_x/2+4,rp2040zero_y/2+2]
        - ref: mirror_trrs
          shift: [trrs_x/2,-trrs_y/2]
        - ref: mirror_thumbs_outer_cluster
          shift: [0.75px,-0.5py]
        - ref: mirror_thumbs_outer_cluster
          shift: [-0.75px,-0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [-0.75px,0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [0.9px,0.5py]
        - ref: mirror_matrix_ring_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
  board:
    - boardLeft
    - boardRight
  boarda:
    - what: rectangle
      where: /matrix/
      size: [kx+boardPadding,ky+boardPadding]
    - what: rectangle
      where: /thumb/
      size: [1.5kx+boardPadding,ky+boardPadding]
    - what: rectangle
      where: /mcu/
      size: [rp2040zero_x+8, rp2040zero_y+5]
    - what: rectangle
      where: /mcu/
      size: [rp2040zero_x+16, rp2040zero_y+20]
      adjust:
        shift: [-4,-7.5]
  _mcu:
    - what: rectangle
      where: /mcu/
      size: [rp2040zero_x, rp2040zero_y]
  _trrs:
    - what: rectangle
      where: /trrs/
      size: [trrs_x, trrs_y] 
  xlBoard:
    - what: outline
      name: board
      expand: wallThickness
  mounting:
    - what: circle
      where: /hole/
      radius: screwRadius
  standoff:
    - what: outline
      name: mounting
      expand: standoffThickness
  combo:
    - xlBoard
    - ^board
    - ^keys
    - ^_mcu
    - ^_trrs
    #- ^standoff
    #- ^mounting
pcbs:
  chouchou:
    outlines:
      main:
        outline:
          board
    footprints:
      chocHotswapLeft:
        what: choc
        where: /^(thumb|matrix)/
        params:
          keycaps: true
          hotswap: true
          from: "{{name}}"
          to: GND
      chocLeft:
        what: choc
        where: /^(thumb|matrix)/
        adjust:
          rotate: 180
        params:
          keycaps: true
          from: "{{name}}"
          to: GND
      chocHotswapRight:
        what: choc
        where: /^mirror_(thumb|matrix)/
        params:
          keycaps: true
          hotswap: true
          from: "{{name}}"
          to: rGND
      chocRight:
        what: choc
        where: /^mirror_(thumb|matrix)/
        adjust:
          rotate: 180
        params:
          keycaps: true
          from: "{{name}}"
          to: rGND
      mcuLeft:
        what: rp2040zero
        where: mcu
        adjust:
          shift: [-rp2040zero_x / 2, -rp2040zero_y / 2]
        params:
          reverse: true
          P5V: P5V
          GND: GND
          P3V3: P3V3
          GP29: GP29
          GP28: matrix_index_top
          GP27: matrix_middle_top
          GP26: matrix_ring_top
          GP15: matrix_pinky_top
          GP14: matrix_index_bottom
          GP13: matrix_middle_bottom
          GP12: matrix_ring_bottom
          GP11: matrix_pinky_bottom
          GP10: thumbs_inner_cluster
          GP9: thumbs_outer_cluster
          GP8: GP8
          GP7: GP7
          GP6: GP6
          GP5: RX
          GP4: TX
          GP3: GP3
          GP2: GP2
          GP1: GP1
          GP0: GP0
      mcuRight:
        what: rp2040zero
        where: mirror_mcu
        adjust:
          shift: [rp2040zero_x / 2 + 2.5, -rp2040zero_y / 2]
        params:
          P5V: rP5V
          GND: rGND
          P3V3: rP3V3
          GP29: rGND
          GP28: rGP28
          GP27: rGP27
          GP26: rGP26
          GP15: rGP15
          GP14: rGP14
          GP13: rRX
          GP12: rTX
          GP11: rGP11
          GP10: rGP10
          GP9: mirror_thumbs_outer_cluster
          GP8: mirror_thumbs_inner_cluster
          GP7: mirror_matrix_pinky_bottom
          GP6: mirror_matrix_ring_bottom
          GP5: mirror_matrix_middle_bottom
          GP4: mirror_matrix_index_bottom
          GP3: mirror_matrix_pinky_top
          GP2: mirror_matrix_ring_top
          GP1: mirror_matrix_middle_top
          GP0: mirror_matrix_index_top
      trrsLeft:
        what: trrs
        where: trrs
        adjust:
          rotate: -90
          shift: [trrs_x / 2, -trrs_y / 2 + 2]
        params:
          A: GND
          B: P3V3
          C: RX
          D: TX
      trrsRight:
        what: trrs
        where: mirror_trrs
        adjust:
          rotate: -90
          shift: [trrs_x / 2, 3.5]
        params:
          A: rGND
          B: rP3V3
          C: rRX
          D: rTX
      #holes:
      #  what: mountinghole
      #  where: /hole/
cases:
  bottom:
    - name: xlBoard
      extrude: baseThickness
  _outerWall:
    - name: xlBoard
      extrude: baseThickness + standoffDepth + pcbThickness
  _innerWall:
    - name: board
      extrude: baseThickness + standoffDepth + pcbThickness
  wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
  _holes:
    - name: mounting
      extrude: baseThickness + standoffDepth
  _standoffs:
    - name: standoff
      extrude: baseThickness + standoffDepth
  case:
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
    - what: case
      name: bottom
      operation: add
    - what: case
      name: wall
      operation: add 