units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 2
  py: ky + 2
  # Double Padding Variables
  dpx: kx + 8
  dpy: ky + 8
  # M2 Screw Inserts
  screwRadius: 1.5
  standoffThickness: 3
  standoffDepth: 3
  # Case
  pcbThickness: 1.6
  baseThickness: 3
  wallThickness: 3
points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      key:
        padding: 1ky
      columns:
        pinky:
          key:
            splay: 8
          rows:
            top.mcuLeft_pin: GP26
            bottom.mcuLeft_pin: GP12
            top.mirror.mcuRight_pin: rGP26
            bottom.mirror.mcuRight_pin: rGP12
        ring:
          key:
            stagger: 4
            spread: 23
            splay: -4
          rows:
            top.mcuLeft_pin: GP27
            bottom.mcuLeft_pin: GP13
            top.mirror.mcuRight_pin: rGP27
            bottom.mirror.mcuRight_pin: rGP13
        middle:
          key:
            stagger: 5
            spread: 20
            splay: -4
          rows:
            top.mcuLeft_pin: GP28
            bottom.mcuLeft_pin: GP14
            top.mirror.mcuRight_pin: rGP28
            bottom.mirror.mcuRight_pin: rGP14
        index:
          key:
            stagger: -8
            spread: 20
            splay: -4
          rows:
            top.mcuLeft_pin: GP29
            bottom.mcuLeft_pin: GP15
            top.mirror.mcuRight_pin: rGP29
            bottom.mirror.mcuRight_pin: rGP15
      rows:
        bottom:
        top:
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_index_bottom
        shift: [8, 0]
      columns:
        inner:
          key:
            width: 1.5kx
            splay: 4
            rotate: 90
            mcuLeft_pin: GP11
            mirror.mcuRight_pin: rGP11
        outer:
          key:
            width: 1.5kx
            rotate: 90
            mcuLeft_pin: GP10
            mirror.mcuRight_pin: rGP10
      rows:
        cluster:
          shift: [0, -2ky]
  mirror: &mirror
    ref: matrix_index_top
    distance: 80
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
    - what: rectangle
      where: thumbs_inner_cluster
      size: [1.5kx,ky-0.5]
    - what: rectangle
      where: thumbs_outer_cluster
      size: [1.5kx,ky-0.5]
    - what: rectangle
      where: mirror_thumbs_inner_cluster
      size: [1.5kx,ky-0.5]
    - what: rectangle
      where: mirror_thumbs_outer_cluster
      size: [1.5kx,ky-0.5]
  board_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: thumbs_outer_cluster
          shift: [2.75px,-0.5py]
        - ref: thumbs_outer_cluster
          shift: [0.75px,-0.5py]
        - ref: thumbs_outer_cluster
          shift: [-0.75px,-0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.75px,-0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.75px,0.5py]
        - ref: thumbs_inner_cluster
          shift: [1.2px,0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
  board_right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [1.2px,0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [0.75px,0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [-0.75px,0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [-0.75px,-0.5py]
        - ref: mirror_thumbs_outer_cluster
          shift: [-0.75px,-0.5py]
        - ref: mirror_thumbs_outer_cluster
          shift: [0.75px,-0.5py]
        - ref: mirror_thumbs_outer_cluster
          shift: [2.75px,-0.5py]
  board:
    - name: board_left
    - name: board_right
  xlBoard:
    - what: outline
      name: board
      expand: wallThickness
  combo:
    - name: board
    - operation: subtract
      name: keys
  case:
    - name: xlBoard
    - operation: subtract
      name: board
    - operation: add
      name: keys
  mounting:
    holeTopLeft:
      radius: screwRadius
      what: circle
      where:
        ref: [matrix_pinky_top]
        shift: [0.5px + 3,0.5py + 3]
    holeTopRight:
      radius: screwRadius
      what: circle
      where:
        ref: [mirror_matrix_pinky_top]
        shift: [0.5px + 3,0.5py + 3]
    holeBottomLeft:
      radius: screwRadius
      what: circle
      where:
        ref: [matrix_middle_bottom]
        shift: [0,-0.5py - 3]
    holeBottomRight:
      radius: screwRadius
      what: circle
      where:
        ref: [mirror_matrix_middle_bottom]
        shift: [0,-0.5py - 3]
    holeMiddleTopLeft:
      radius: screwRadius
      what: circle
      where:
        ref: [matrix_index_top]
        shift: [-0.5px - 3, 11]
    holeMiddleTopRight:
      radius: screwRadius
      what: circle
      where:
        ref: [mirror_matrix_index_top]
        shift: [-0.5px - 3, 11]
    holeMiddleBottomLeft:
      radius: screwRadius
      what: circle
      where:
        ref: [thumbs_outer_cluster]
        shift: [-0.5kx - 3, 0.5kx]
    holeMiddleBottomRight:
      radius: screwRadius
      what: circle
      where:
        ref: [mirror_thumbs_outer_cluster]
        shift: [-0.5kx - 3, 0.5kx]
  standoff:
    - what: outline
      name: mounting
      expand: standoffThickness
pcbs:
  chouchou:
    outlines:
      main:
        outline:
          board
    footprints:
      chocHotswapLeft:
        what: choc
        where: /^(thumb|matrix)/
        params:
          keycaps: true
          hotswap: true
          from: "{{mcuLeft_pin}}"
          to: GND
      chocLeft:
        what: choc
        where: /^(thumb|matrix)/
        adjust:
          rotate: 180
        params:
          keycaps: true
          from: "{{mcuLeft_pin}}"
          to: GND
      chocHotswapRight:
        what: choc
        where: /^mirror/
        params:
          keycaps: true
          hotswap: true
          from: "{{mcuRight_pin}}"
          to: rGND
      chocRight:
        what: choc
        where: /^mirror/
        adjust:
          rotate: 180
        params:
          keycaps: true
          from: "{{mcuRight_pin}}"
          to: rGND
      mcuLeft:
        what: rp2040zero
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-28,-22]
      mcuRight:
        what: rp2040zero
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [8,-22]
        params:
          P5V: rP5V
          GND: rGND
          P3V3: rP3V3
          GP29: rGP29
          GP28: rGP28
          GP27: rGP27
          GP26: rGP26
          GP15: rGP15
          GP14: rGP14
          GP13: rGP13
          GP12: rGP12
          GP11: rGP11
          GP10: rGP10
          GP9: rGP9
          GP8: rGP8
          GP7: rGP7
          GP6: rGP6
          GP5: rGP5
          GP4: rGP4
          GP3: rGP3
          GP2: rGP2
          GP1: rGP1
          GP0: rGP0
      holeTopLeft:
        what: mountinghole
        where:
          ref: [matrix_pinky_top]
          shift: [0.5px + 3,0.5py + 3]
      holeTopRight:
        what: mountinghole
        where:
          ref: [mirror_matrix_pinky_top]
          shift: [0.5px + 3,0.5py + 3]
      holeBottomLeft:
        what: mountinghole
        where:
          ref: [matrix_middle_bottom]
          shift: [0,-0.5py - 3]
      holeBottomRight:
        what: mountinghole
        where:
          ref: [mirror_matrix_middle_bottom]
          shift: [0,-0.5py - 3]
      holeMiddleTopLeft:
        what: mountinghole
        where:
          ref: [matrix_index_top]
          shift: [-0.5px - 3, 11]
      holeMiddleTopRight:
        what: mountinghole
        where:
          ref: [mirror_matrix_index_top]
          shift: [-0.5px - 3, 11]
      holeMiddleBottomLeft:
        what: mountinghole
        where:
          ref: [thumbs_outer_cluster]
          shift: [-0.5kx - 3, 0.5kx]
      holeMiddleBottomRight:
        what: mountinghole
        where:
          ref: [mirror_thumbs_outer_cluster]
          shift: [-0.5kx - 3, 0.5kx]
cases:
  bottom:
    - name: xlBoard
      extrude: baseThickness
  _outerWall:
    - name: xlBoard
      extrude: baseThickness + standoffDepth + pcbThickness
  _innerWall:
    - name: board
      extrude: baseThickness + standoffDepth + pcbThickness
  wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
  _holes:
    - name: mounting
      extrude: baseThickness + standoffDepth
  _standoffs:
    - name: standoff
      extrude: baseThickness + standoffDepth
  case:
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
    - what: case
      name: bottom
      operation: add
    - what: case
      name: wall
      operation: add