units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 2
  py: ky + 2
  # Double Padding Variables
  dpx: kx + 8
  dpy: ky + 8
  # M2 Screw Inserts
  screwRadius: 1.5
  standoffThickness: 3
  standoffDepth: 3
  # Case
  pcbThickness: 1.6
  baseThickness: 3
  wallThickness: 3
  # Footprints
  rp2040zero_x: 18
  rp2040zero_y: 23.5
points:
  zones:
    matrix:
      anchor:
        shift: [50, -80]
      key:
        padding: 1ky
      columns:
        pinky:
          key:
            splay: 8
        ring:
          key:
            stagger: 4
            spread: 23
            splay: -4
        middle:
          key:
            stagger: 5
            spread: 20
            splay: -4
        index:
          key:
            stagger: -8
            spread: 20
            splay: -4
      rows:
        bottom:
        top:
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_index_bottom
        shift: [8, 0]
      columns:
        inner:
          key:
            width: 1.5kx
            splay: 4
            rotate: 90
        outer:
          key:
            width: 1.5kx
            rotate: 90
      rows:
        cluster:
          shift: [0, -2ky]
    mcu:
      anchor:
        ref: matrix_index_top
        shift: [22, -10]
      key:
        width: rp2040zero_x
        height: rp2040zero_y
        rotate: 4
    holePinkyTop:
      anchor:
        ref: [matrix_pinky_top]
        shift: [0.5px + 2,0.5py + 1]
    holeMiddleBottom:
      anchor:
        ref: [matrix_middle_bottom]
        shift: [0,-0.5py - 3]
    holeIndexTop:
      anchor:
        ref: [matrix_index_top]
        shift: [-0.2px, 12]
    holeThumbs:
      anchor:
        ref: [thumbs_outer_cluster]
        shift: [-0.5kx - 3, 0.5kx]
  mirror: &mirror
    ref: matrix_index_top
    distance: 80
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: /matrix/
      size: [kx-0.5,ky-0.5]
    - what: rectangle
      where: /thumb/
      size: [1.5kx,ky-0.5]
  board_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: thumbs_outer_cluster
          shift: [2.75px,-0.5py]
        - ref: thumbs_outer_cluster
          shift: [0.75px,-0.5py]
        - ref: thumbs_outer_cluster
          shift: [-0.75px,-0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.75px,-0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.75px,0.5py]
        - ref: thumbs_inner_cluster
          shift: [1.2px,0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
  board_right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [1.2px,0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [0.75px,0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [-0.75px,0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [-0.75px,-0.5py]
        - ref: mirror_thumbs_outer_cluster
          shift: [-0.75px,-0.5py]
        - ref: mirror_thumbs_outer_cluster
          shift: [0.75px,-0.5py]
        - ref: mirror_thumbs_outer_cluster
          shift: [2.75px,-0.5py]
  board:
    - board_left
    - board_right
  _mcu:
    - what: rectangle
      where: /mcu/
      size: [rp2040zero_x, rp2040zero_y]
  xlBoard:
    - what: outline
      name: board
      expand: wallThickness
  mounting:
    - what: circle
      where: /hole/
      radius: screwRadius
  standoff:
    - what: outline
      name: mounting
      expand: standoffThickness
  combo:
    - xlBoard
    - ^board
    - ^keys
    - ^_mcu
    - ^mounting
pcbs:
  chouchou:
    outlines:
      main:
        outline:
          board
    footprints:
      chocHotswap:
        what: choc
        where: /(thumb|matrix)/
        params:
          keycaps: true
          hotswap: true
          from: "{{name}}"
          to: GND
      choc:
        what: choc
        where: /(thumb|matrix)/
        adjust:
          rotate: 180
        params:
          keycaps: true
          from: "{{name}}"
          to: GND
      mcuLeft:
        what: rp2040zero
        where: mcu
        adjust:
          shift: [-rp2040zero_x / 2, -rp2040zero_y / 2]
        params:
          reverse: true
          P5V: P5V
          GND: GND
          P3V3: P3V3
          GP29: GP29
          GP28: matrix_index_top
          GP27: matrix_middle_top
          GP26: matrix_ring_top
          GP15: matrix_pinky_top
          GP14: matrix_index_bottom
          GP13: matrix_middle_bottom
          GP12: matrix_ring_bottom
          GP11: matrix_pinky_bottom
          GP10: thumbs_inner_cluster
          GP9: thumbs_outer_cluster
          GP8: GP8
          GP7: GP7
          GP6: GP6
          GP5: GP5
          GP4: GP4
          GP3: GP3
          GP2: GP2
          GP1: GP1
          GP0: GP0
      mcuRight:
        what: rp2040zero
        where: mirror_mcu
        adjust:
          shift: [rp2040zero_x / 2 + 2.5, -rp2040zero_y / 2]
        params:
          P5V: rP5V
          GND: rGND
          P3V3: rP3V3
          GP29: rGP29
          GP28: rGP28
          GP27: rGP27
          GP26: rGP26
          GP15: rGP15
          GP14: rGP14
          GP13: rGP13
          GP12: rGP12
          GP11: rGP11
          GP10: rGP10
          GP9: mirror_thumbs_outer_cluster
          GP8: mirror_thumbs_inner_cluster
          GP7: mirror_matrix_pinky_bottom
          GP6: mirror_matrix_ring_bottom
          GP5: mirror_matrix_middle_bottom
          GP4: mirror_matrix_index_bottom
          GP3: mirror_matrix_pinky_top
          GP2: mirror_matrix_ring_top
          GP1: mirror_matrix_middle_top
          GP0: mirror_matrix_index_top
      holes:
        what: mountinghole
        where: /hole/
cases:
  bottom:
    - name: xlBoard
      extrude: baseThickness
  _outerWall:
    - name: xlBoard
      extrude: baseThickness + standoffDepth + pcbThickness
  _innerWall:
    - name: board
      extrude: baseThickness + standoffDepth + pcbThickness
  wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
  _holes:
    - name: mounting
      extrude: baseThickness + standoffDepth
  _standoffs:
    - name: standoff
      extrude: baseThickness + standoffDepth
  case:
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
    - what: case
      name: bottom
      operation: add
    - what: case
      name: wall
      operation: add