units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 2
  py: ky + 2
  # Double Padding Variables
  dpx: kx + 8
  dpy: ky + 8
  # M2 Screw Inserts
  screwRadius: 1.5
  standoffThickness: 3
  standoffDepth: 3
  # Case
  pcbThickness: 1.6
  baseThickness: 3
  wallThickness: 3
  # Footprints
  rp2040zero_x: 18
  rp2040zero_y: 23.5
  jumper_x: 1
  jumper_y: 2
points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      key:
        padding: 1ky
      columns:
        pinky:
          key:
            splay: 8
          rows:
            top.mcuLeft_pin: GP26
            bottom.mcuLeft_pin: GP12
        ring:
          key:
            stagger: 4
            spread: 23
            splay: -4
          rows:
            top.mcuLeft_pin: GP27
            bottom.mcuLeft_pin: GP13
        middle:
          key:
            stagger: 5
            spread: 20
            splay: -4
          rows:
            top.mcuLeft_pin: GP28
            bottom.mcuLeft_pin: GP14
        index:
          key:
            stagger: -8
            spread: 20
            splay: -4
          rows:
            top.mcuLeft_pin: GP29
            bottom.mcuLeft_pin: GP15
      rows:
        bottom:
        top:
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_index_bottom
        shift: [8, 0]
      columns:
        inner:
          key:
            width: 1.5kx
            splay: 4
            rotate: 90
            mcuLeft_pin: GP11
        outer:
          key:
            width: 1.5kx
            rotate: 90
            mcuLeft_pin: GP10
      rows:
        cluster:
          shift: [0, -2ky]
    mcu:
      anchor:
        ref: [thumbs_outer_cluster]
        shift: [40, 3]
        rotate: -90
      key:
        width: rp2040zero_x
        height: rp2040zero_y
    jumper:
      anchor:
        ref: [mcu]
        shift: [7, 6]
      key:
        width: jumper_x
        height: jumper_y
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: /^matrix/
      size: [kx-0.5,ky-0.5]
    - what: rectangle
      where: /^thumb/
      size: [1.5kx,ky-0.5]
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: thumbs_outer_cluster
          shift: [2.75px,-0.5py]
        - ref: thumbs_outer_cluster
          shift: [0.75px,-0.5py]
        - ref: thumbs_outer_cluster
          shift: [-0.75px,-0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.75px,-0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.75px,0.5py]
        - ref: thumbs_inner_cluster
          shift: [1.2px,0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
  _mcu:
    - what: rectangle
      where: mcu
      size: [rp2040zero_x, rp2040zero_y]
  _jumper:
    - what: rectangle
      where: jumper
      size: [jumper_x, jumper_y]
  xlBoard:
    - what: outline
      name: board
      expand: wallThickness
  combo:
    - board
    - ^keys
    - ^_mcu
    - ^_jumper
  case:
    - name: xlBoard
    - operation: subtract
      name: board
    - operation: add
      name: keys
  mounting:
    holeTopLeft:
      radius: screwRadius
      what: circle
      where:
        ref: [matrix_pinky_top]
        shift: [0.5px + 3,0.5py + 3]
    holeBottomLeft:
      radius: screwRadius
      what: circle
      where:
        ref: [matrix_middle_bottom]
        shift: [0,-0.5py - 3]
    holeMiddleTopLeft:
      radius: screwRadius
      what: circle
      where:
        ref: [matrix_index_top]
        shift: [-0.5px - 3, 11]
    holeMiddleBottomLeft:
      radius: screwRadius
      what: circle
      where:
        ref: [thumbs_outer_cluster]
        shift: [-0.5kx - 3, 0.5kx]
  standoff:
    - what: outline
      name: mounting
      expand: standoffThickness
pcbs:
  chouchou:
    outlines:
      main:
        outline:
          board
    footprints:
      jumper:
        what: jumper
        where: jumper
        adjust:
          rotate: 90
        params:
          designator: right_indicator
          from: GP3
          to: GND
      chocHotswapLeft:
        what: choc
        where: /^(thumb|matrix)/
        params:
          keycaps: true
          hotswap: true
          from: "{{mcuLeft_pin}}"
          to: GND
      chocLeft:
        what: choc
        where: /^(thumb|matrix)/
        adjust:
          rotate: 180
        params:
          keycaps: true
          from: "{{mcuLeft_pin}}"
          to: GND
      mcu:
        what: rp2040zero
        where: mcu
        adjust:
          shift: [-rp2040zero_x / 2, -rp2040zero_y / 2]
        params:
          GP1: GND
      holeTopLeft:
        what: mountinghole
        where:
          ref: [matrix_pinky_top]
          shift: [0.5px + 3,0.5py + 3]
      holeBottomLeft:
        what: mountinghole
        where:
          ref: [matrix_middle_bottom]
          shift: [0,-0.5py - 3]
      holeMiddleTopLeft:
        what: mountinghole
        where:
          ref: [matrix_index_top]
          shift: [-0.5px - 3, 11]
      holeMiddleBottomLeft:
        what: mountinghole
        where:
          ref: [thumbs_outer_cluster]
          shift: [-0.5kx - 3, 0.5kx]
cases:
  bottom:
    - name: xlBoard
      extrude: baseThickness
  _outerWall:
    - name: xlBoard
      extrude: baseThickness + standoffDepth + pcbThickness
  _innerWall:
    - name: board
      extrude: baseThickness + standoffDepth + pcbThickness
  wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
  _holes:
    - name: mounting
      extrude: baseThickness + standoffDepth
  _standoffs:
    - name: standoff
      extrude: baseThickness + standoffDepth
  case:
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
    - what: case
      name: bottom
      operation: add
    - what: case
      name: wall
      operation: add